### ISSUE TITLE
Dependencies on git creates problem for nodejs-slim docker container.

### ISSUE THREAD

**Issue by tommymalmqvist** [chartjs/color#2]
Hi,

The official nodejs slim docker containers do not have git installed by default. This creates a problem with the following dependencies:

http://github.com/harthur/color.git
https://github.com/chartjs/color-string.git

Do we have to use git to retrieve this?

**Comment by etimberg** [comment]
@tommymalmqvist we could update those forked dependencies to install via npm.

**Comment by tommymalmqvist** [comment]
@etimberg That would help a lot, I'd rather not install git in the nodejs slim container.

**Comment by etimberg** [comment]
@tommymalmqvist yeah, we shouldn't require that.

**Comment by tommymalmqvist** [comment]
Do we have any news on this?

**Comment by etimberg** [comment]
@tommymalmqvist I've fixed this. I pushed a v0.5.0 of this lib that pulls in the color-string library via NPM. This library is pulled into Chart.js via npm, so everything should be good to go

**Comment by tommymalmqvist** [comment]
@etimberg amazing! Thank you 🍾
